export default {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "avatar-user-squareolivia-rhye-color-background":
          "var(--avatar-user-squareolivia-rhye-color-background)",
        "avatar-user-squarephoenix-baker-color-background":
          "var(--avatar-user-squarephoenix-baker-color-background)",
        black: "var(--black)",
        "blue-400": "var(--blue-400)",
        "blue-50": "var(--blue-50)",
        "blue-500": "var(--blue-500)",
        "blue-600": "var(--blue-600)",
        "blue-gray900": "var(--blue-gray900)",
        "blue-light500": "var(--blue-light500)",
        "brand-5": "var(--brand-5)",
        "brand-60": "var(--brand-60)",
        dark: "var(--dark)",
        "destructive-50": "var(--destructive-50)",
        "error-100": "var(--error-100)",
        "error-25": "var(--error-25)",
        "error-300": "var(--error-300)",
        "error-50": "var(--error-50)",
        "error-500": "var(--error-500)",
        "error-600": "var(--error-600)",
        "error-700": "var(--error-700)",
        "gray-100": "var(--gray-100)",
        "gray-20": "var(--gray-20)",
        "gray-200": "var(--gray-200)",
        "gray-25": "var(--gray-25)",
        "gray-30": "var(--gray-30)",
        "gray-300": "var(--gray-300)",
        "gray-40": "var(--gray-40)",
        "gray-400": "var(--gray-400)",
        "gray-5": "var(--gray-5)",
        "gray-50": "var(--gray-50)",
        "gray-500": "var(--gray-500)",
        "gray-60": "var(--gray-60)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-80": "var(--gray-80)",
        "gray-800": "var(--gray-800)",
        "gray-900": "var(--gray-900)",
        "gray0-white": "var(--gray0-white)",
        "gray100-black": "var(--gray100-black)",
        "grey-100": "var(--grey-100)",
        "grey-700": "var(--grey-700)",
        "greygrey-3": "var(--greygrey-3)",
        "indigo-50": "var(--indigo-50)",
        "indigo-600": "var(--indigo-600)",
        "main-primary100": "var(--main-primary100)",
        "orange-200": "var(--orange-200)",
        "orange-400": "var(--orange-400)",
        "primary-100": "var(--primary-100)",
        "primary-200": "var(--primary-200)",
        "primary-25": "var(--primary-25)",
        "primary-300": "var(--primary-300)",
        "primary-400": "var(--primary-400)",
        "primary-50": "var(--primary-50)",
        "primary-500": "var(--primary-500)",
        "primary-600": "var(--primary-600)",
        "primary-700": "var(--primary-700)",
        "primary-800": "var(--primary-800)",
        "redred-1": "var(--redred-1)",
        shadeblack: "var(--shadeblack)",
        shadewhite: "var(--shadewhite)",
        "success-100": "var(--success-100)",
        "success-20": "var(--success-20)",
        "success-5": "var(--success-5)",
        "success-50": "var(--success-50)",
        "success-500": "var(--success-500)",
        "success-600": "var(--success-600)",
        "success-700": "var(--success-700)",
        "transparentblack-32": "var(--transparentblack-32)",
        "transparentwhite-32": "var(--transparentwhite-32)",
        "warning-100": "var(--warning-100)",
        "warning-400": "var(--warning-400)",
        "warning-50": "var(--warning-50)",
        "warning-500": "var(--warning-500)",
        "warning-600": "var(--warning-600)",
        "warning-900": "var(--warning-900)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        'mona-sans': ['Mona Sans', 'sans-serif'],
        "display-lg-medium": "var(--display-lg-medium-font-family)",
        "display-md-semibold": "var(--display-md-semibold-font-family)",
        "display-sm-bold": "var(--display-sm-bold-font-family)",
        "display-sm-medium": "var(--display-sm-medium-font-family)",
        "display-sm-semibold": "var(--display-sm-semibold-font-family)",
        "display-xs-bold": "var(--display-xs-bold-font-family)",
        "display-xs-medium": "var(--display-xs-medium-font-family)",
        "display-xs-normal": "var(--display-xs-normal-font-family)",
        "display-xs-semibold": "var(--display-xs-semibold-font-family)",
        "text-lg-bold": "var(--text-lg-bold-font-family)",
        "text-lg-medium": "var(--text-lg-medium-font-family)",
        "text-lg-medium-underlined":
          "var(--text-lg-medium-underlined-font-family)",
        "text-lg-semibold": "var(--text-lg-semibold-font-family)",
        "text-md-bold": "var(--text-md-bold-font-family)",
        "text-md-medium": "var(--text-md-medium-font-family)",
        "text-md-normal": "var(--text-md-normal-font-family)",
        "text-md-semibold": "var(--text-md-semibold-font-family)",
        "text-sm-bold": "var(--text-sm-bold-font-family)",
        "text-sm-medium": "var(--text-sm-medium-font-family)",
        "text-sm-normal": "var(--text-sm-normal-font-family)",
        "text-sm-semibold": "var(--text-sm-semibold-font-family)",
        "text-xl-bold": "var(--text-xl-bold-font-family)",
        "text-xl-medium": "var(--text-xl-medium-font-family)",
        "text-xl-normal": "var(--text-xl-normal-font-family)",
        "text-xl-regular-underlined":
          "var(--text-xl-regular-underlined-font-family)",
        "text-xl-semibold": "var(--text-xl-semibold-font-family)",
        "text-xs-medium": "var(--text-xs-medium-font-family)",
        "text-xs-normal": "var(--text-xs-normal-font-family)",
        "text-xs-semibold": "var(--text-xs-semibold-font-family)",
        sans: [
           "Mona Sans",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "background-blur-md": "var(--background-blur-md)",
        "background-blur-sm": "var(--background-blur-sm)",
        "blur-background-md": "var(--blur-background-md)",
        "shadow-lg": "var(--shadow-lg)",
        "shadow-md": "var(--shadow-md)",
        "shadow-sm": "var(--shadow-sm)",
        "shadow-xl": "var(--shadow-xl)",
        "shadow-xs": "var(--shadow-xs)",
        "shadow-xs-focused-4px-primary-100":
          "var(--shadow-xs-focused-4px-primary-100)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
